---
controller_credential_types:
  - name: OCP Bearer Token
    description: OCP Bearer Token
    inputs:
      fields:
        - id: host
          type: string
          label: Kubernetes API Host
        - id: bearer_token
          type: string
          label: Bearer Token
          secret: true
        - id: verify_ssl
          type: boolean
          label: Verify SSL
        - id: ssl_ca_cert
          type: string
          label: SSL CA Certificate
          secret: true
          multiline: true
      required:
        - host
        - bearer_token
    injectors:
      env:
        K8S_AUTH_HOST: !unsafe '{{ host }}'
        K8S_AUTH_API_KEY: !unsafe '{{ bearer_token }}'
        K8S_AUTH_VERIFY_SSL: !unsafe '{{ verify_ssl }}'
      file:
        template.ssl_ca_cert: !unsafe '{{ ssl_ca_cert }}'